/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['barcode', 'categoryId', 'costPrice', 'createdAt', 'description', 'id', 'minimumQuantity', 'name', 'price', 'quantity', 'sku', 'supplierId', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare barcode: string | null
  @column()
  declare categoryId: number
  @column()
  declare costPrice: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minimumQuantity: number | null
  @column()
  declare name: string
  @column()
  declare price: number
  @column()
  declare quantity: number
  @column()
  declare sku: string
  @column()
  declare supplierId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockMovementSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'quantity', 'reason', 'type', 'updatedAt', 'userId'] as const
  $columns = StockMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare reason: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SupplierSchema extends BaseModel {
  static $columns = ['address', 'cnpj', 'createdAt', 'email', 'id', 'name', 'phone', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare cnpj: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
